spring.application.name=parentai-backend

# ??????? ?? ????????? (????? ???????? dev, ????? ?? ???????? ????????)
spring.profiles.active=prod

# ===== ????? ????????? ??????? =====
server.port=8080

# ===== JWT =====
jwt.secret=super_secret_key_change_me_please_1234567890
jwt.expiration-ms=86400000
